# Test configuration - 1 epoch only
data:
  instrument_dir: "C:\\SoundBanks\\IthacaPlayer\\instrument"
  sample_rate: 48000
  audio_length: 3.0
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  type: "gan"
  latent_dim: 128
  hidden_dims: [128, 256, 512, 1024]
  midi_note_range: [33, 94]
  velocity_levels: 8
  use_mel_spectrogram: true
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  gan:
    generator_base_channels: 256
    discriminator_base_channels: 64
    use_spectral_norm: true
    num_res_blocks: 3

training:
  batch_size: 4  # Smaller for faster test
  num_epochs: 1  # TEST: Only 1 epoch
  learning_rate: 0.0002
  weight_decay: 0.0001
  generator_lr: 0.0002
  discriminator_lr: 0.0002
  reconstruction_weight: 1.0
  kl_weight: 0.001
  gan_loss_type: "hinge"
  optimizer: "adam"
  scheduler: "reduce_on_plateau"
  patience: 15
  save_every: 1  # Save after 1 epoch for testing
  checkpoint_dir: "checkpoints"
  log_every: 10  # Log more frequently
  tensorboard_dir: "logs"

inference:
  output_dir: "outputs"
  output_sample_rate: 48000
  output_bit_depth: 16
  vocoder_type: "hifigan"
  griffin_lim_iterations: 300
  hifigan_checkpoint: null
  default_temperature: 1.0
  use_variable_length: true

style_transfer:
  enabled: false
  reference_track: null
  spectral_loss_weight: 1.0
  perceptual_loss_weight: 0.5
